# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1223x729")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 729,
    width = 1223,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    422.0,
    729.0,
    fill="#FC5353",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    211.0,
    259.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    823.0,
    319.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_1.place(
    x=529.0,
    y=300.0,
    width=588.0,
    height=37.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    823.0,
    160.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    highlightthickness=0
)
entry_2.place(
    x=529.0,
    y=141.0,
    width=588.0,
    height=37.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
quitWindow  = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=window.destroy,
    relief="flat"
)
quitWindow .place(
    x=57.0,
    y=591.0,
    width=307.34075927734375,
    height=45.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
trackImg = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=TrackImages,
    relief="flat"
)
trackImg.place(
    x=57.0,
    y=439.0,
    width=307.0,
    height=45.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
takeImg  = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=TakeImages,
    relief="flat"
)
takeImg.place(
    x=517.0,
    y=589.0,
    width=240.0,
    height=45.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
trainImg = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=psw,
    relief="flat"
)
trainImg.place(
    x=889.0,
    y=591.0,
    width=240.0,
    height=45.0
)

canvas.create_text(
    753.0,
    259.0,
    anchor="nw",
    text="USER NAME",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    743.0,
    100.0,
    anchor="nw",
    text="NRC NUMBER",
    fill="#000000",
    font=("Inter", 24 * -1)
)

canvas.create_text(
    14.0,
    20.0,
    anchor="nw",
    text="FACE MASK AND FACIAL",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    87.0,
    59.0,
    anchor="nw",
    text="RECOGNITION",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    91.0,
    98.0,
    anchor="nw",
    text="ATTENDANCE",
    fill="#FFFFFF",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    699.0,
    20.0,
    anchor="nw",
    text="REGISTER USER",
    fill="#000000",
    font=("Inter SemiBold", 32 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
clearButton = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=clear,
    relief="flat"
)
clearButton.place(
    x=521.0,
    y=438.0,
    width=240.0,
    height=46.3365478515625
)
window.resizable(False, False)
window.mainloop()
